// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deactivateDeviceToken = `-- name: DeactivateDeviceToken :exec
UPDATE device_tokens
SET is_active = false, updated_at = now()
WHERE id = $1 AND user_id = $2
`

type DeactivateDeviceTokenParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeactivateDeviceToken(ctx context.Context, arg DeactivateDeviceTokenParams) error {
	_, err := q.db.ExecContext(ctx, deactivateDeviceToken, arg.ID, arg.UserID)
	return err
}

const getActiveDeviceTokens = `-- name: GetActiveDeviceTokens :many
SELECT id, user_id, token, platform, is_active, created_at, updated_at FROM device_tokens
WHERE user_id = $1 AND is_active = true
`

func (q *Queries) GetActiveDeviceTokens(ctx context.Context, userID uuid.UUID) ([]DeviceToken, error) {
	rows, err := q.db.QueryContext(ctx, getActiveDeviceTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceToken{}
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Platform,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :one
INSERT INTO device_tokens (user_id, token, platform, is_active)
VALUES ($1, $2, $3, true)
ON CONFLICT (token) DO UPDATE
    SET user_id   = EXCLUDED.user_id,
        platform  = EXCLUDED.platform,
        is_active = true,
        updated_at = now()
RETURNING id, user_id, token, platform, is_active, created_at, updated_at
`

type UpsertDeviceTokenParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Token    string    `json:"token"`
	Platform string    `json:"platform"`
}

func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (DeviceToken, error) {
	row := q.db.QueryRowContext(ctx, upsertDeviceToken, arg.UserID, arg.Token, arg.Platform)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Platform,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
