// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: follow_ups.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createFollowUp = `-- name: CreateFollowUp :one
INSERT INTO follow_ups (
    id, user_id, log_id, person_id, title, due_date, status,
    is_recurring, recurrence_interval_days, recurrence_type
)
VALUES ($1, $2, $3, $4, $5, $6, 'pending', $7, $8, $9)
RETURNING id, user_id, log_id, person_id, title, due_date, status, snoozed_until, completed_at, is_recurring, recurrence_interval_days, recurrence_type, source_type, created_at, updated_at, deleted_at
`

type CreateFollowUpParams struct {
	ID                     uuid.UUID      `json:"id"`
	UserID                 uuid.UUID      `json:"user_id"`
	LogID                  uuid.NullUUID  `json:"log_id"`
	PersonID               uuid.NullUUID  `json:"person_id"`
	Title                  string         `json:"title"`
	DueDate                time.Time      `json:"due_date"`
	IsRecurring            bool           `json:"is_recurring"`
	RecurrenceIntervalDays sql.NullInt32  `json:"recurrence_interval_days"`
	RecurrenceType         sql.NullString `json:"recurrence_type"`
}

func (q *Queries) CreateFollowUp(ctx context.Context, arg CreateFollowUpParams) (FollowUp, error) {
	row := q.db.QueryRowContext(ctx, createFollowUp,
		arg.ID,
		arg.UserID,
		arg.LogID,
		arg.PersonID,
		arg.Title,
		arg.DueDate,
		arg.IsRecurring,
		arg.RecurrenceIntervalDays,
		arg.RecurrenceType,
	)
	var i FollowUp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LogID,
		&i.PersonID,
		&i.Title,
		&i.DueDate,
		&i.Status,
		&i.SnoozedUntil,
		&i.CompletedAt,
		&i.IsRecurring,
		&i.RecurrenceIntervalDays,
		&i.RecurrenceType,
		&i.SourceType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDueFollowUps = `-- name: GetDueFollowUps :many
SELECT id, user_id, log_id, person_id, title, due_date, status, snoozed_until, completed_at, is_recurring, recurrence_interval_days, recurrence_type, source_type, created_at, updated_at, deleted_at FROM follow_ups
WHERE status = 'due' AND deleted_at IS NULL
`

func (q *Queries) GetDueFollowUps(ctx context.Context) ([]FollowUp, error) {
	rows, err := q.db.QueryContext(ctx, getDueFollowUps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FollowUp{}
	for rows.Next() {
		var i FollowUp
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LogID,
			&i.PersonID,
			&i.Title,
			&i.DueDate,
			&i.Status,
			&i.SnoozedUntil,
			&i.CompletedAt,
			&i.IsRecurring,
			&i.RecurrenceIntervalDays,
			&i.RecurrenceType,
			&i.SourceType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowUpByID = `-- name: GetFollowUpByID :one
SELECT id, user_id, log_id, person_id, title, due_date, status, snoozed_until, completed_at, is_recurring, recurrence_interval_days, recurrence_type, source_type, created_at, updated_at, deleted_at FROM follow_ups
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetFollowUpByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetFollowUpByID(ctx context.Context, arg GetFollowUpByIDParams) (FollowUp, error) {
	row := q.db.QueryRowContext(ctx, getFollowUpByID, arg.ID, arg.UserID)
	var i FollowUp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LogID,
		&i.PersonID,
		&i.Title,
		&i.DueDate,
		&i.Status,
		&i.SnoozedUntil,
		&i.CompletedAt,
		&i.IsRecurring,
		&i.RecurrenceIntervalDays,
		&i.RecurrenceType,
		&i.SourceType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFollowUpsByUpdatedSince = `-- name: GetFollowUpsByUpdatedSince :many
SELECT id, user_id, log_id, person_id, title, due_date, status, snoozed_until, completed_at, is_recurring, recurrence_interval_days, recurrence_type, source_type, created_at, updated_at, deleted_at FROM follow_ups
WHERE user_id = $1 AND updated_at > $2
ORDER BY updated_at ASC
LIMIT $3
`

type GetFollowUpsByUpdatedSinceParams struct {
	UserID    uuid.UUID `json:"user_id"`
	UpdatedAt time.Time `json:"updated_at"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) GetFollowUpsByUpdatedSince(ctx context.Context, arg GetFollowUpsByUpdatedSinceParams) ([]FollowUp, error) {
	rows, err := q.db.QueryContext(ctx, getFollowUpsByUpdatedSince, arg.UserID, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FollowUp{}
	for rows.Next() {
		var i FollowUp
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LogID,
			&i.PersonID,
			&i.Title,
			&i.DueDate,
			&i.Status,
			&i.SnoozedUntil,
			&i.CompletedAt,
			&i.IsRecurring,
			&i.RecurrenceIntervalDays,
			&i.RecurrenceType,
			&i.SourceType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowUps = `-- name: ListFollowUps :many
SELECT id, user_id, log_id, person_id, title, due_date, status, snoozed_until, completed_at, is_recurring, recurrence_interval_days, recurrence_type, source_type, created_at, updated_at, deleted_at FROM follow_ups
WHERE user_id = $1
  AND deleted_at IS NULL
  AND ($2::text = '' OR status = $2)
ORDER BY due_date ASC
LIMIT $3 OFFSET $4
`

type ListFollowUpsParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Column2 string    `json:"column_2"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListFollowUps(ctx context.Context, arg ListFollowUpsParams) ([]FollowUp, error) {
	rows, err := q.db.QueryContext(ctx, listFollowUps,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FollowUp{}
	for rows.Next() {
		var i FollowUp
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LogID,
			&i.PersonID,
			&i.Title,
			&i.DueDate,
			&i.Status,
			&i.SnoozedUntil,
			&i.CompletedAt,
			&i.IsRecurring,
			&i.RecurrenceIntervalDays,
			&i.RecurrenceType,
			&i.SourceType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFollowUpsDue = `-- name: MarkFollowUpsDue :many
UPDATE follow_ups
SET status = 'due', updated_at = now()
WHERE status IN ('pending', 'snoozed')
  AND due_date <= CURRENT_DATE
  AND (snoozed_until IS NULL OR snoozed_until <= CURRENT_DATE)
  AND deleted_at IS NULL
RETURNING id, user_id, log_id, person_id, title, due_date, status, snoozed_until, completed_at, is_recurring, recurrence_interval_days, recurrence_type, source_type, created_at, updated_at, deleted_at
`

func (q *Queries) MarkFollowUpsDue(ctx context.Context) ([]FollowUp, error) {
	rows, err := q.db.QueryContext(ctx, markFollowUpsDue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FollowUp{}
	for rows.Next() {
		var i FollowUp
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LogID,
			&i.PersonID,
			&i.Title,
			&i.DueDate,
			&i.Status,
			&i.SnoozedUntil,
			&i.CompletedAt,
			&i.IsRecurring,
			&i.RecurrenceIntervalDays,
			&i.RecurrenceType,
			&i.SourceType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteFollowUp = `-- name: SoftDeleteFollowUp :one
UPDATE follow_ups
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, log_id, person_id, title, due_date, status, snoozed_until, completed_at, is_recurring, recurrence_interval_days, recurrence_type, source_type, created_at, updated_at, deleted_at
`

type SoftDeleteFollowUpParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteFollowUp(ctx context.Context, arg SoftDeleteFollowUpParams) (FollowUp, error) {
	row := q.db.QueryRowContext(ctx, softDeleteFollowUp, arg.ID, arg.UserID)
	var i FollowUp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LogID,
		&i.PersonID,
		&i.Title,
		&i.DueDate,
		&i.Status,
		&i.SnoozedUntil,
		&i.CompletedAt,
		&i.IsRecurring,
		&i.RecurrenceIntervalDays,
		&i.RecurrenceType,
		&i.SourceType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateFollowUp = `-- name: UpdateFollowUp :one
UPDATE follow_ups
SET title                    = coalesce($3, title),
    due_date                 = coalesce($4, due_date),
    status                   = coalesce($5, status),
    snoozed_until            = coalesce($6, snoozed_until),
    completed_at             = coalesce($7, completed_at),
    updated_at               = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, log_id, person_id, title, due_date, status, snoozed_until, completed_at, is_recurring, recurrence_interval_days, recurrence_type, source_type, created_at, updated_at, deleted_at
`

type UpdateFollowUpParams struct {
	ID           uuid.UUID      `json:"id"`
	UserID       uuid.UUID      `json:"user_id"`
	Title        sql.NullString `json:"title"`
	DueDate      sql.NullTime   `json:"due_date"`
	Status       sql.NullString `json:"status"`
	SnoozedUntil sql.NullTime   `json:"snoozed_until"`
	CompletedAt  sql.NullTime   `json:"completed_at"`
}

func (q *Queries) UpdateFollowUp(ctx context.Context, arg UpdateFollowUpParams) (FollowUp, error) {
	row := q.db.QueryRowContext(ctx, updateFollowUp,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.DueDate,
		arg.Status,
		arg.SnoozedUntil,
		arg.CompletedAt,
	)
	var i FollowUp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LogID,
		&i.PersonID,
		&i.Title,
		&i.DueDate,
		&i.Status,
		&i.SnoozedUntil,
		&i.CompletedAt,
		&i.IsRecurring,
		&i.RecurrenceIntervalDays,
		&i.RecurrenceType,
		&i.SourceType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertFollowUp = `-- name: UpsertFollowUp :one
INSERT INTO follow_ups (
    id, user_id, log_id, person_id, title, due_date, status,
    snoozed_until, is_recurring, recurrence_interval_days, recurrence_type,
    created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, now())
ON CONFLICT (id) DO UPDATE
    SET title                    = EXCLUDED.title,
        due_date                 = EXCLUDED.due_date,
        status                   = EXCLUDED.status,
        snoozed_until            = EXCLUDED.snoozed_until,
        is_recurring             = EXCLUDED.is_recurring,
        recurrence_interval_days = EXCLUDED.recurrence_interval_days,
        recurrence_type          = EXCLUDED.recurrence_type,
        updated_at               = now(),
        deleted_at               = NULL
WHERE follow_ups.updated_at <= EXCLUDED.updated_at
RETURNING id, user_id, log_id, person_id, title, due_date, status, snoozed_until, completed_at, is_recurring, recurrence_interval_days, recurrence_type, source_type, created_at, updated_at, deleted_at
`

type UpsertFollowUpParams struct {
	ID                     uuid.UUID      `json:"id"`
	UserID                 uuid.UUID      `json:"user_id"`
	LogID                  uuid.NullUUID  `json:"log_id"`
	PersonID               uuid.NullUUID  `json:"person_id"`
	Title                  string         `json:"title"`
	DueDate                time.Time      `json:"due_date"`
	Status                 string         `json:"status"`
	SnoozedUntil           sql.NullTime   `json:"snoozed_until"`
	IsRecurring            bool           `json:"is_recurring"`
	RecurrenceIntervalDays sql.NullInt32  `json:"recurrence_interval_days"`
	RecurrenceType         sql.NullString `json:"recurrence_type"`
	CreatedAt              time.Time      `json:"created_at"`
}

func (q *Queries) UpsertFollowUp(ctx context.Context, arg UpsertFollowUpParams) (FollowUp, error) {
	row := q.db.QueryRowContext(ctx, upsertFollowUp,
		arg.ID,
		arg.UserID,
		arg.LogID,
		arg.PersonID,
		arg.Title,
		arg.DueDate,
		arg.Status,
		arg.SnoozedUntil,
		arg.IsRecurring,
		arg.RecurrenceIntervalDays,
		arg.RecurrenceType,
		arg.CreatedAt,
	)
	var i FollowUp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LogID,
		&i.PersonID,
		&i.Title,
		&i.DueDate,
		&i.Status,
		&i.SnoozedUntil,
		&i.CompletedAt,
		&i.IsRecurring,
		&i.RecurrenceIntervalDays,
		&i.RecurrenceType,
		&i.SourceType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
