// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: follow_ups.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const upsertFollowUp = `-- name: UpsertFollowUp :one
INSERT INTO follow_ups (
    id, user_id, log_id, person_id, title, due_date, status,
    snoozed_until, is_recurring, recurrence_interval_days, recurrence_type,
    created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, now())
ON CONFLICT (id) DO UPDATE
    SET title                    = EXCLUDED.title,
        due_date                 = EXCLUDED.due_date,
        status                   = EXCLUDED.status,
        snoozed_until            = EXCLUDED.snoozed_until,
        is_recurring             = EXCLUDED.is_recurring,
        recurrence_interval_days = EXCLUDED.recurrence_interval_days,
        recurrence_type          = EXCLUDED.recurrence_type,
        updated_at               = now(),
        deleted_at               = NULL
WHERE follow_ups.updated_at <= EXCLUDED.updated_at
RETURNING id, user_id, log_id, person_id, title, due_date, status, snoozed_until, completed_at, is_recurring, recurrence_interval_days, recurrence_type, source_type, created_at, updated_at, deleted_at`

type UpsertFollowUpParams struct {
	ID                     uuid.UUID  `json:"id"`
	UserID                 uuid.UUID  `json:"user_id"`
	LogID                  *uuid.UUID `json:"log_id"`
	PersonID               *uuid.UUID `json:"person_id"`
	Title                  string     `json:"title"`
	DueDate                time.Time  `json:"due_date"`
	Status                 string     `json:"status"`
	SnoozedUntil           *time.Time `json:"snoozed_until"`
	IsRecurring            bool       `json:"is_recurring"`
	RecurrenceIntervalDays *int32     `json:"recurrence_interval_days"`
	RecurrenceType         *string    `json:"recurrence_type"`
	CreatedAt              time.Time  `json:"created_at"`
}

func (q *Queries) UpsertFollowUp(ctx context.Context, arg UpsertFollowUpParams) (FollowUp, error) {
	row := q.db.QueryRow(ctx, upsertFollowUp,
		arg.ID, arg.UserID, arg.LogID, arg.PersonID, arg.Title, arg.DueDate,
		arg.Status, arg.SnoozedUntil, arg.IsRecurring,
		arg.RecurrenceIntervalDays, arg.RecurrenceType, arg.CreatedAt,
	)
	return scanFollowUp(row)
}

const softDeleteFollowUp = `-- name: SoftDeleteFollowUp :one
UPDATE follow_ups
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, log_id, person_id, title, due_date, status, snoozed_until, completed_at, is_recurring, recurrence_interval_days, recurrence_type, source_type, created_at, updated_at, deleted_at`

func (q *Queries) SoftDeleteFollowUp(ctx context.Context, id, userID uuid.UUID) (FollowUp, error) {
	row := q.db.QueryRow(ctx, softDeleteFollowUp, id, userID)
	return scanFollowUp(row)
}

const getFollowUpsByUpdatedSince = `-- name: GetFollowUpsByUpdatedSince :many
SELECT id, user_id, log_id, person_id, title, due_date, status, snoozed_until, completed_at, is_recurring, recurrence_interval_days, recurrence_type, source_type, created_at, updated_at, deleted_at
FROM follow_ups
WHERE user_id = $1 AND updated_at > $2
ORDER BY updated_at ASC
LIMIT $3`

type GetFollowUpsByUpdatedSinceParams struct {
	UserID    uuid.UUID `json:"user_id"`
	UpdatedAt time.Time `json:"updated_at"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) GetFollowUpsByUpdatedSince(ctx context.Context, arg GetFollowUpsByUpdatedSinceParams) ([]FollowUp, error) {
	rows, err := q.db.Query(ctx, getFollowUpsByUpdatedSince, arg.UserID, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FollowUp
	for rows.Next() {
		i, err := scanFollowUpRow(rows)
		if err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const listFollowUps = `-- name: ListFollowUps :many
SELECT id, user_id, log_id, person_id, title, due_date, status, snoozed_until, completed_at, is_recurring, recurrence_interval_days, recurrence_type, source_type, created_at, updated_at, deleted_at
FROM follow_ups
WHERE user_id = $1
  AND deleted_at IS NULL
  AND ($2::text = '' OR status = $2)
ORDER BY due_date ASC
LIMIT $3 OFFSET $4`

type ListFollowUpsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Status string    `json:"status"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListFollowUps(ctx context.Context, arg ListFollowUpsParams) ([]FollowUp, error) {
	rows, err := q.db.Query(ctx, listFollowUps, arg.UserID, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FollowUp
	for rows.Next() {
		i, err := scanFollowUpRow(rows)
		if err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getFollowUpByID = `-- name: GetFollowUpByID :one
SELECT id, user_id, log_id, person_id, title, due_date, status, snoozed_until, completed_at, is_recurring, recurrence_interval_days, recurrence_type, source_type, created_at, updated_at, deleted_at
FROM follow_ups
WHERE id = $1 AND user_id = $2
LIMIT 1`

func (q *Queries) GetFollowUpByID(ctx context.Context, id, userID uuid.UUID) (FollowUp, error) {
	row := q.db.QueryRow(ctx, getFollowUpByID, id, userID)
	return scanFollowUp(row)
}

const updateFollowUp = `-- name: UpdateFollowUp :one
UPDATE follow_ups
SET title         = coalesce($3, title),
    due_date      = coalesce($4, due_date),
    status        = coalesce($5, status),
    snoozed_until = coalesce($6, snoozed_until),
    completed_at  = coalesce($7, completed_at),
    updated_at    = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, log_id, person_id, title, due_date, status, snoozed_until, completed_at, is_recurring, recurrence_interval_days, recurrence_type, source_type, created_at, updated_at, deleted_at`

type UpdateFollowUpParams struct {
	ID           uuid.UUID  `json:"id"`
	UserID       uuid.UUID  `json:"user_id"`
	Title        *string    `json:"title"`
	DueDate      *time.Time `json:"due_date"`
	Status       *string    `json:"status"`
	SnoozedUntil *time.Time `json:"snoozed_until"`
	CompletedAt  *time.Time `json:"completed_at"`
}

func (q *Queries) UpdateFollowUp(ctx context.Context, arg UpdateFollowUpParams) (FollowUp, error) {
	row := q.db.QueryRow(ctx, updateFollowUp,
		arg.ID, arg.UserID, arg.Title, arg.DueDate,
		arg.Status, arg.SnoozedUntil, arg.CompletedAt,
	)
	return scanFollowUp(row)
}

const markFollowUpsDue = `-- name: MarkFollowUpsDue :many
UPDATE follow_ups
SET status = 'due', updated_at = now()
WHERE status IN ('pending', 'snoozed')
  AND due_date <= CURRENT_DATE
  AND (snoozed_until IS NULL OR snoozed_until <= CURRENT_DATE)
  AND deleted_at IS NULL
RETURNING id, user_id, log_id, person_id, title, due_date, status, snoozed_until, completed_at, is_recurring, recurrence_interval_days, recurrence_type, source_type, created_at, updated_at, deleted_at`

func (q *Queries) MarkFollowUpsDue(ctx context.Context) ([]FollowUp, error) {
	rows, err := q.db.Query(ctx, markFollowUpsDue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FollowUp
	for rows.Next() {
		i, err := scanFollowUpRow(rows)
		if err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getDueFollowUps = `-- name: GetDueFollowUps :many
SELECT id, user_id, log_id, person_id, title, due_date, status, snoozed_until, completed_at, is_recurring, recurrence_interval_days, recurrence_type, source_type, created_at, updated_at, deleted_at
FROM follow_ups
WHERE status = 'due' AND deleted_at IS NULL`

func (q *Queries) GetDueFollowUps(ctx context.Context) ([]FollowUp, error) {
	rows, err := q.db.Query(ctx, getDueFollowUps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FollowUp
	for rows.Next() {
		i, err := scanFollowUpRow(rows)
		if err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const createFollowUp = `-- name: CreateFollowUp :one
INSERT INTO follow_ups (
    id, user_id, log_id, person_id, title, due_date, status,
    is_recurring, recurrence_interval_days, recurrence_type
)
VALUES ($1, $2, $3, $4, $5, $6, 'pending', $7, $8, $9)
RETURNING id, user_id, log_id, person_id, title, due_date, status, snoozed_until, completed_at, is_recurring, recurrence_interval_days, recurrence_type, source_type, created_at, updated_at, deleted_at`

type CreateFollowUpParams struct {
	ID                     uuid.UUID  `json:"id"`
	UserID                 uuid.UUID  `json:"user_id"`
	LogID                  *uuid.UUID `json:"log_id"`
	PersonID               *uuid.UUID `json:"person_id"`
	Title                  string     `json:"title"`
	DueDate                time.Time  `json:"due_date"`
	IsRecurring            bool       `json:"is_recurring"`
	RecurrenceIntervalDays *int32     `json:"recurrence_interval_days"`
	RecurrenceType         *string    `json:"recurrence_type"`
}

func (q *Queries) CreateFollowUp(ctx context.Context, arg CreateFollowUpParams) (FollowUp, error) {
	row := q.db.QueryRow(ctx, createFollowUp,
		arg.ID, arg.UserID, arg.LogID, arg.PersonID, arg.Title, arg.DueDate,
		arg.IsRecurring, arg.RecurrenceIntervalDays, arg.RecurrenceType,
	)
	return scanFollowUp(row)
}

// scanFollowUp scans a single FollowUp from a pgx.Row.
func scanFollowUp(row interface {
	Scan(dest ...any) error
}) (FollowUp, error) {
	var i FollowUp
	err := row.Scan(
		&i.ID, &i.UserID, &i.LogID, &i.PersonID, &i.Title, &i.DueDate,
		&i.Status, &i.SnoozedUntil, &i.CompletedAt, &i.IsRecurring,
		&i.RecurrenceIntervalDays, &i.RecurrenceType, &i.SourceType,
		&i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
	)
	return i, err
}

// scanFollowUpRow scans a FollowUp from pgx.Rows (used in loops).
func scanFollowUpRow(rows interface {
	Scan(dest ...any) error
}) (FollowUp, error) {
	return scanFollowUp(rows)
}
