// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: important_dates.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createImportantDate = `-- name: CreateImportantDate :one
INSERT INTO person_important_dates (
    id, user_id, person_id, label, is_birthday,
    month, day, year,
    reminder_offset_days, reminder_recurrence, note,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11,
    now(), now()
)
RETURNING id, user_id, person_id, label, is_birthday, month, day, year, reminder_offset_days, reminder_recurrence, note, created_at, updated_at, deleted_at
`

type CreateImportantDateParams struct {
	ID                 uuid.UUID      `json:"id"`
	UserID             uuid.UUID      `json:"user_id"`
	PersonID           uuid.UUID      `json:"person_id"`
	Label              string         `json:"label"`
	IsBirthday         bool           `json:"is_birthday"`
	Month              int32          `json:"month"`
	Day                int32          `json:"day"`
	Year               sql.NullInt32  `json:"year"`
	ReminderOffsetDays sql.NullInt32  `json:"reminder_offset_days"`
	ReminderRecurrence sql.NullString `json:"reminder_recurrence"`
	Note               sql.NullString `json:"note"`
}

func (q *Queries) CreateImportantDate(ctx context.Context, arg CreateImportantDateParams) (PersonImportantDate, error) {
	row := q.db.QueryRowContext(ctx, createImportantDate,
		arg.ID,
		arg.UserID,
		arg.PersonID,
		arg.Label,
		arg.IsBirthday,
		arg.Month,
		arg.Day,
		arg.Year,
		arg.ReminderOffsetDays,
		arg.ReminderRecurrence,
		arg.Note,
	)
	var i PersonImportantDate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PersonID,
		&i.Label,
		&i.IsBirthday,
		&i.Month,
		&i.Day,
		&i.Year,
		&i.ReminderOffsetDays,
		&i.ReminderRecurrence,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getImportantDate = `-- name: GetImportantDate :one
SELECT id, user_id, person_id, label, is_birthday, month, day, year, reminder_offset_days, reminder_recurrence, note, created_at, updated_at, deleted_at FROM person_important_dates
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetImportantDateParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetImportantDate(ctx context.Context, arg GetImportantDateParams) (PersonImportantDate, error) {
	row := q.db.QueryRowContext(ctx, getImportantDate, arg.ID, arg.UserID)
	var i PersonImportantDate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PersonID,
		&i.Label,
		&i.IsBirthday,
		&i.Month,
		&i.Day,
		&i.Year,
		&i.ReminderOffsetDays,
		&i.ReminderRecurrence,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listImportantDatesByPerson = `-- name: ListImportantDatesByPerson :many
SELECT id, user_id, person_id, label, is_birthday, month, day, year, reminder_offset_days, reminder_recurrence, note, created_at, updated_at, deleted_at FROM person_important_dates
WHERE person_id = $1 AND user_id = $2 AND deleted_at IS NULL
ORDER BY is_birthday DESC, month ASC, day ASC
`

type ListImportantDatesByPersonParams struct {
	PersonID uuid.UUID `json:"person_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) ListImportantDatesByPerson(ctx context.Context, arg ListImportantDatesByPersonParams) ([]PersonImportantDate, error) {
	rows, err := q.db.QueryContext(ctx, listImportantDatesByPerson, arg.PersonID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PersonImportantDate{}
	for rows.Next() {
		var i PersonImportantDate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PersonID,
			&i.Label,
			&i.IsBirthday,
			&i.Month,
			&i.Day,
			&i.Year,
			&i.ReminderOffsetDays,
			&i.ReminderRecurrence,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportantDatesByUserSince = `-- name: ListImportantDatesByUserSince :many
SELECT id, user_id, person_id, label, is_birthday, month, day, year, reminder_offset_days, reminder_recurrence, note, created_at, updated_at, deleted_at FROM person_important_dates
WHERE user_id = $1 AND updated_at > $2
ORDER BY updated_at ASC
`

type ListImportantDatesByUserSinceParams struct {
	UserID    uuid.UUID `json:"user_id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ListImportantDatesByUserSince(ctx context.Context, arg ListImportantDatesByUserSinceParams) ([]PersonImportantDate, error) {
	rows, err := q.db.QueryContext(ctx, listImportantDatesByUserSince, arg.UserID, arg.UpdatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PersonImportantDate{}
	for rows.Next() {
		var i PersonImportantDate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PersonID,
			&i.Label,
			&i.IsBirthday,
			&i.Month,
			&i.Day,
			&i.Year,
			&i.ReminderOffsetDays,
			&i.ReminderRecurrence,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteImportantDate = `-- name: SoftDeleteImportantDate :exec
UPDATE person_important_dates
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteImportantDateParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteImportantDate(ctx context.Context, arg SoftDeleteImportantDateParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteImportantDate, arg.ID, arg.UserID)
	return err
}

const updateImportantDate = `-- name: UpdateImportantDate :one
UPDATE person_important_dates
SET label                = $3,
    is_birthday          = $4,
    month                = $5,
    day                  = $6,
    year                 = $7,
    reminder_offset_days = $8,
    reminder_recurrence  = $9,
    note                 = $10,
    updated_at           = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, person_id, label, is_birthday, month, day, year, reminder_offset_days, reminder_recurrence, note, created_at, updated_at, deleted_at
`

type UpdateImportantDateParams struct {
	ID                 uuid.UUID      `json:"id"`
	UserID             uuid.UUID      `json:"user_id"`
	Label              string         `json:"label"`
	IsBirthday         bool           `json:"is_birthday"`
	Month              int32          `json:"month"`
	Day                int32          `json:"day"`
	Year               sql.NullInt32  `json:"year"`
	ReminderOffsetDays sql.NullInt32  `json:"reminder_offset_days"`
	ReminderRecurrence sql.NullString `json:"reminder_recurrence"`
	Note               sql.NullString `json:"note"`
}

func (q *Queries) UpdateImportantDate(ctx context.Context, arg UpdateImportantDateParams) (PersonImportantDate, error) {
	row := q.db.QueryRowContext(ctx, updateImportantDate,
		arg.ID,
		arg.UserID,
		arg.Label,
		arg.IsBirthday,
		arg.Month,
		arg.Day,
		arg.Year,
		arg.ReminderOffsetDays,
		arg.ReminderRecurrence,
		arg.Note,
	)
	var i PersonImportantDate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PersonID,
		&i.Label,
		&i.IsBirthday,
		&i.Month,
		&i.Day,
		&i.Year,
		&i.ReminderOffsetDays,
		&i.ReminderRecurrence,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
