// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: logs.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getLogByID = `-- name: GetLogByID :one
SELECT id, user_id, content, type, status, day_id, device_id, created_at, updated_at, deleted_at
FROM logs
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetLogByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetLogByIDRow struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Content   string       `json:"content"`
	Type      string       `json:"type"`
	Status    string       `json:"status"`
	DayID     time.Time    `json:"day_id"`
	DeviceID  string       `json:"device_id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

func (q *Queries) GetLogByID(ctx context.Context, arg GetLogByIDParams) (GetLogByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getLogByID, arg.ID, arg.UserID)
	var i GetLogByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.Type,
		&i.Status,
		&i.DayID,
		&i.DeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLogsByUpdatedSince = `-- name: GetLogsByUpdatedSince :many
SELECT id, user_id, content, type, status, day_id, device_id, created_at, updated_at, deleted_at
FROM logs
WHERE user_id = $1 AND updated_at > $2
ORDER BY updated_at ASC
LIMIT $3
`

type GetLogsByUpdatedSinceParams struct {
	UserID    uuid.UUID `json:"user_id"`
	UpdatedAt time.Time `json:"updated_at"`
	Limit     int32     `json:"limit"`
}

type GetLogsByUpdatedSinceRow struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Content   string       `json:"content"`
	Type      string       `json:"type"`
	Status    string       `json:"status"`
	DayID     time.Time    `json:"day_id"`
	DeviceID  string       `json:"device_id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

func (q *Queries) GetLogsByUpdatedSince(ctx context.Context, arg GetLogsByUpdatedSinceParams) ([]GetLogsByUpdatedSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, getLogsByUpdatedSince, arg.UserID, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLogsByUpdatedSinceRow{}
	for rows.Next() {
		var i GetLogsByUpdatedSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.Type,
			&i.Status,
			&i.DayID,
			&i.DeviceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogs = `-- name: ListLogs :many
SELECT id, user_id, content, type, status, day_id, device_id, created_at, updated_at, deleted_at
FROM logs
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY day_id DESC
LIMIT $2 OFFSET $3
`

type ListLogsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListLogsRow struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Content   string       `json:"content"`
	Type      string       `json:"type"`
	Status    string       `json:"status"`
	DayID     time.Time    `json:"day_id"`
	DeviceID  string       `json:"device_id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

func (q *Queries) ListLogs(ctx context.Context, arg ListLogsParams) ([]ListLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLogs, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLogsRow{}
	for rows.Next() {
		var i ListLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.Type,
			&i.Status,
			&i.DayID,
			&i.DeviceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteLog = `-- name: SoftDeleteLog :one
UPDATE logs
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, content, type, status, day_id, device_id, created_at, updated_at, deleted_at
`

type SoftDeleteLogParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type SoftDeleteLogRow struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Content   string       `json:"content"`
	Type      string       `json:"type"`
	Status    string       `json:"status"`
	DayID     time.Time    `json:"day_id"`
	DeviceID  string       `json:"device_id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

func (q *Queries) SoftDeleteLog(ctx context.Context, arg SoftDeleteLogParams) (SoftDeleteLogRow, error) {
	row := q.db.QueryRowContext(ctx, softDeleteLog, arg.ID, arg.UserID)
	var i SoftDeleteLogRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.Type,
		&i.Status,
		&i.DayID,
		&i.DeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateLog = `-- name: UpdateLog :one
UPDATE logs
SET content    = coalesce($3, content),
    type       = coalesce($4, type),
    status     = coalesce($5, status),
    updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, content, type, status, day_id, device_id, created_at, updated_at, deleted_at
`

type UpdateLogParams struct {
	ID      uuid.UUID      `json:"id"`
	UserID  uuid.UUID      `json:"user_id"`
	Content sql.NullString `json:"content"`
	Type    sql.NullString `json:"type"`
	Status  sql.NullString `json:"status"`
}

type UpdateLogRow struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Content   string       `json:"content"`
	Type      string       `json:"type"`
	Status    string       `json:"status"`
	DayID     time.Time    `json:"day_id"`
	DeviceID  string       `json:"device_id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

func (q *Queries) UpdateLog(ctx context.Context, arg UpdateLogParams) (UpdateLogRow, error) {
	row := q.db.QueryRowContext(ctx, updateLog,
		arg.ID,
		arg.UserID,
		arg.Content,
		arg.Type,
		arg.Status,
	)
	var i UpdateLogRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.Type,
		&i.Status,
		&i.DayID,
		&i.DeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertLog = `-- name: UpsertLog :one
INSERT INTO logs (id, user_id, content, type, status, day_id, device_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
ON CONFLICT (id) DO UPDATE
    SET content    = EXCLUDED.content,
        type       = EXCLUDED.type,
        status     = EXCLUDED.status,
        day_id     = EXCLUDED.day_id,
        device_id  = EXCLUDED.device_id,
        updated_at = now(),
        deleted_at = NULL
WHERE logs.updated_at <= EXCLUDED.updated_at
RETURNING id, user_id, content, type, status, day_id, device_id, created_at, updated_at, deleted_at
`

type UpsertLogParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Content   string    `json:"content"`
	Type      string    `json:"type"`
	Status    string    `json:"status"`
	DayID     time.Time `json:"day_id"`
	DeviceID  string    `json:"device_id"`
	CreatedAt time.Time `json:"created_at"`
}

type UpsertLogRow struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Content   string       `json:"content"`
	Type      string       `json:"type"`
	Status    string       `json:"status"`
	DayID     time.Time    `json:"day_id"`
	DeviceID  string       `json:"device_id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

func (q *Queries) UpsertLog(ctx context.Context, arg UpsertLogParams) (UpsertLogRow, error) {
	row := q.db.QueryRowContext(ctx, upsertLog,
		arg.ID,
		arg.UserID,
		arg.Content,
		arg.Type,
		arg.Status,
		arg.DayID,
		arg.DeviceID,
		arg.CreatedAt,
	)
	var i UpsertLogRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.Type,
		&i.Status,
		&i.DayID,
		&i.DeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
