// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID           uuid.UUID  `json:"id"`
	Email        string     `json:"email"`
	PasswordHash string     `json:"password_hash"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	DeletedAt    *time.Time `json:"deleted_at"`
}

type RefreshToken struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Person struct {
	ID                  uuid.UUID  `json:"id"`
	UserID              uuid.UUID  `json:"user_id"`
	Name                string     `json:"name"`
	Notes               *string    `json:"notes"`
	LastInteractionDate *time.Time `json:"last_interaction_date"`
	CreatedAt           time.Time  `json:"created_at"`
	UpdatedAt           time.Time  `json:"updated_at"`
	DeletedAt           *time.Time `json:"deleted_at"`
}

type Log struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	Content   string     `json:"content"`
	Type      string     `json:"type"`
	Status    string     `json:"status"`
	DayID     time.Time  `json:"day_id"`
	DeviceID  string     `json:"device_id"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type LogPersonLink struct {
	ID        uuid.UUID `json:"id"`
	LogID     uuid.UUID `json:"log_id"`
	PersonID  uuid.UUID `json:"person_id"`
	UserID    uuid.UUID `json:"user_id"`
	LinkType  string    `json:"link_type"`
	CreatedAt time.Time `json:"created_at"`
}

type FollowUp struct {
	ID                      uuid.UUID  `json:"id"`
	UserID                  uuid.UUID  `json:"user_id"`
	LogID                   *uuid.UUID `json:"log_id"`
	PersonID                *uuid.UUID `json:"person_id"`
	Title                   string     `json:"title"`
	DueDate                 time.Time  `json:"due_date"`
	Status                  string     `json:"status"`
	SnoozedUntil            *time.Time `json:"snoozed_until"`
	CompletedAt             *time.Time `json:"completed_at"`
	IsRecurring             bool       `json:"is_recurring"`
	RecurrenceIntervalDays  *int32     `json:"recurrence_interval_days"`
	RecurrenceType          *string    `json:"recurrence_type"`
	SourceType              *string    `json:"source_type"`
	CreatedAt               time.Time  `json:"created_at"`
	UpdatedAt               time.Time  `json:"updated_at"`
	DeletedAt               *time.Time `json:"deleted_at"`
}

type Notification struct {
	ID          uuid.UUID  `json:"id"`
	UserID      uuid.UUID  `json:"user_id"`
	FollowUpID  *uuid.UUID `json:"follow_up_id"`
	Title       string     `json:"title"`
	Body        string     `json:"body"`
	Status      string     `json:"status"`
	RetryCount  int32      `json:"retry_count"`
	MaxRetries  int32      `json:"max_retries"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

type NotificationDelivery struct {
	ID              uuid.UUID  `json:"id"`
	NotificationID  uuid.UUID  `json:"notification_id"`
	DeviceTokenID   *uuid.UUID `json:"device_token_id"`
	Status          string     `json:"status"`
	ErrorMessage    *string    `json:"error_message"`
	AttemptedAt     time.Time  `json:"attempted_at"`
}

type DeviceToken struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	Platform  string    `json:"platform"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type UserSetting struct {
	ID                          uuid.UUID `json:"id"`
	UserID                      uuid.UUID `json:"user_id"`
	NotificationsEnabled        bool      `json:"notifications_enabled"`
	DefaultFollowUpDays         int32     `json:"default_follow_up_days"`
	InactivityFollowUpsEnabled  bool      `json:"inactivity_follow_ups_enabled"`
	InactivityThresholdDays     int32     `json:"inactivity_threshold_days"`
	CreatedAt                   time.Time `json:"created_at"`
	UpdatedAt                   time.Time `json:"updated_at"`
}

type SyncMetadatum struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	EntityType  string    `json:"entity_type"`
	DeviceID    string    `json:"device_id"`
	LastSyncAt  time.Time `json:"last_sync_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
