// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: notifications.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, follow_up_id, title, body, status)
VALUES ($1, $2, $3, $4, 'scheduled')
RETURNING id, user_id, follow_up_id, title, body, status, retry_count, max_retries, created_at, updated_at`

type CreateNotificationParams struct {
	UserID     uuid.UUID  `json:"user_id"`
	FollowUpID *uuid.UUID `json:"follow_up_id"`
	Title      string     `json:"title"`
	Body       string     `json:"body"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification, arg.UserID, arg.FollowUpID, arg.Title, arg.Body)
	return scanNotification(row)
}

const getPendingNotifications = `-- name: GetPendingNotifications :many
SELECT id, user_id, follow_up_id, title, body, status, retry_count, max_retries, created_at, updated_at
FROM notifications
WHERE status = 'scheduled'
   OR (status = 'failed' AND retry_count < max_retries)
ORDER BY created_at ASC`

func (q *Queries) GetPendingNotifications(ctx context.Context) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getPendingNotifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		i, err := scanNotificationRow(rows)
		if err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getNotificationsByUser = `-- name: GetNotificationsByUser :many
SELECT id, user_id, follow_up_id, title, body, status, retry_count, max_retries, created_at, updated_at
FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3`

type GetNotificationsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) GetNotificationsByUser(ctx context.Context, arg GetNotificationsByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getNotificationsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		i, err := scanNotificationRow(rows)
		if err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const updateNotificationStatus = `-- name: UpdateNotificationStatus :one
UPDATE notifications
SET status      = $2,
    retry_count = $3,
    updated_at  = now()
WHERE id = $1
RETURNING id, user_id, follow_up_id, title, body, status, retry_count, max_retries, created_at, updated_at`

type UpdateNotificationStatusParams struct {
	ID         uuid.UUID `json:"id"`
	Status     string    `json:"status"`
	RetryCount int32     `json:"retry_count"`
}

func (q *Queries) UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) (Notification, error) {
	row := q.db.QueryRow(ctx, updateNotificationStatus, arg.ID, arg.Status, arg.RetryCount)
	return scanNotification(row)
}

const dismissNotification = `-- name: DismissNotification :one
UPDATE notifications
SET status = 'dismissed', updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, follow_up_id, title, body, status, retry_count, max_retries, created_at, updated_at`

func (q *Queries) DismissNotification(ctx context.Context, id, userID uuid.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, dismissNotification, id, userID)
	return scanNotification(row)
}

func scanNotification(row interface {
	Scan(dest ...any) error
}) (Notification, error) {
	var i Notification
	err := row.Scan(
		&i.ID, &i.UserID, &i.FollowUpID, &i.Title, &i.Body,
		&i.Status, &i.RetryCount, &i.MaxRetries, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

func scanNotificationRow(rows interface {
	Scan(dest ...any) error
}) (Notification, error) {
	return scanNotification(rows)
}

// NotificationDelivery scan helper (used in sync.sql.go)
func scanNotificationDelivery(row interface {
	Scan(dest ...any) error
}) (NotificationDelivery, error) {
	var i NotificationDelivery
	err := row.Scan(
		&i.ID, &i.NotificationID, &i.DeviceTokenID,
		&i.Status, &i.ErrorMessage, &i.AttemptedAt,
	)
	return i, err
}

// Needed for time import in this file — ensure time.Time is referenced
var _ = time.Now
