// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: persons.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getPersonByID = `-- name: GetPersonByID :one
SELECT id, user_id, name, notes, last_interaction_date, created_at, updated_at, deleted_at
FROM persons
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetPersonByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetPersonByIDRow struct {
	ID                  uuid.UUID      `json:"id"`
	UserID              uuid.UUID      `json:"user_id"`
	Name                string         `json:"name"`
	Notes               sql.NullString `json:"notes"`
	LastInteractionDate sql.NullTime   `json:"last_interaction_date"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	DeletedAt           sql.NullTime   `json:"deleted_at"`
}

func (q *Queries) GetPersonByID(ctx context.Context, arg GetPersonByIDParams) (GetPersonByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPersonByID, arg.ID, arg.UserID)
	var i GetPersonByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Notes,
		&i.LastInteractionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPersonsByUpdatedSince = `-- name: GetPersonsByUpdatedSince :many
SELECT id, user_id, name, notes, last_interaction_date, created_at, updated_at, deleted_at
FROM persons
WHERE user_id = $1 AND updated_at > $2
ORDER BY updated_at ASC
LIMIT $3
`

type GetPersonsByUpdatedSinceParams struct {
	UserID    uuid.UUID `json:"user_id"`
	UpdatedAt time.Time `json:"updated_at"`
	Limit     int32     `json:"limit"`
}

type GetPersonsByUpdatedSinceRow struct {
	ID                  uuid.UUID      `json:"id"`
	UserID              uuid.UUID      `json:"user_id"`
	Name                string         `json:"name"`
	Notes               sql.NullString `json:"notes"`
	LastInteractionDate sql.NullTime   `json:"last_interaction_date"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	DeletedAt           sql.NullTime   `json:"deleted_at"`
}

func (q *Queries) GetPersonsByUpdatedSince(ctx context.Context, arg GetPersonsByUpdatedSinceParams) ([]GetPersonsByUpdatedSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, getPersonsByUpdatedSince, arg.UserID, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPersonsByUpdatedSinceRow{}
	for rows.Next() {
		var i GetPersonsByUpdatedSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Notes,
			&i.LastInteractionDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersons = `-- name: ListPersons :many
SELECT id, user_id, name, notes, last_interaction_date, created_at, updated_at, deleted_at
FROM persons
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY name ASC
LIMIT $2 OFFSET $3
`

type ListPersonsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListPersonsRow struct {
	ID                  uuid.UUID      `json:"id"`
	UserID              uuid.UUID      `json:"user_id"`
	Name                string         `json:"name"`
	Notes               sql.NullString `json:"notes"`
	LastInteractionDate sql.NullTime   `json:"last_interaction_date"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	DeletedAt           sql.NullTime   `json:"deleted_at"`
}

func (q *Queries) ListPersons(ctx context.Context, arg ListPersonsParams) ([]ListPersonsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPersons, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonsRow{}
	for rows.Next() {
		var i ListPersonsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Notes,
			&i.LastInteractionDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPersons = `-- name: SearchPersons :many
SELECT id, user_id, name, notes, last_interaction_date, created_at, updated_at, deleted_at
FROM persons
WHERE user_id = $1
  AND deleted_at IS NULL
  AND search_vector @@ plainto_tsquery('english', $2)
ORDER BY ts_rank(search_vector, plainto_tsquery('english', $2)) DESC
LIMIT 50
`

type SearchPersonsParams struct {
	UserID         uuid.UUID `json:"user_id"`
	PlaintoTsquery string    `json:"plainto_tsquery"`
}

type SearchPersonsRow struct {
	ID                  uuid.UUID      `json:"id"`
	UserID              uuid.UUID      `json:"user_id"`
	Name                string         `json:"name"`
	Notes               sql.NullString `json:"notes"`
	LastInteractionDate sql.NullTime   `json:"last_interaction_date"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	DeletedAt           sql.NullTime   `json:"deleted_at"`
}

func (q *Queries) SearchPersons(ctx context.Context, arg SearchPersonsParams) ([]SearchPersonsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPersons, arg.UserID, arg.PlaintoTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPersonsRow{}
	for rows.Next() {
		var i SearchPersonsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Notes,
			&i.LastInteractionDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePerson = `-- name: SoftDeletePerson :one
UPDATE persons
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, name, notes, last_interaction_date, created_at, updated_at, deleted_at
`

type SoftDeletePersonParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type SoftDeletePersonRow struct {
	ID                  uuid.UUID      `json:"id"`
	UserID              uuid.UUID      `json:"user_id"`
	Name                string         `json:"name"`
	Notes               sql.NullString `json:"notes"`
	LastInteractionDate sql.NullTime   `json:"last_interaction_date"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	DeletedAt           sql.NullTime   `json:"deleted_at"`
}

func (q *Queries) SoftDeletePerson(ctx context.Context, arg SoftDeletePersonParams) (SoftDeletePersonRow, error) {
	row := q.db.QueryRowContext(ctx, softDeletePerson, arg.ID, arg.UserID)
	var i SoftDeletePersonRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Notes,
		&i.LastInteractionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePerson = `-- name: UpdatePerson :one
UPDATE persons
SET name       = coalesce($3, name),
    notes      = coalesce($4, notes),
    updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, name, notes, last_interaction_date, created_at, updated_at, deleted_at
`

type UpdatePersonParams struct {
	ID     uuid.UUID      `json:"id"`
	UserID uuid.UUID      `json:"user_id"`
	Name   sql.NullString `json:"name"`
	Notes  sql.NullString `json:"notes"`
}

type UpdatePersonRow struct {
	ID                  uuid.UUID      `json:"id"`
	UserID              uuid.UUID      `json:"user_id"`
	Name                string         `json:"name"`
	Notes               sql.NullString `json:"notes"`
	LastInteractionDate sql.NullTime   `json:"last_interaction_date"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	DeletedAt           sql.NullTime   `json:"deleted_at"`
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) (UpdatePersonRow, error) {
	row := q.db.QueryRowContext(ctx, updatePerson,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Notes,
	)
	var i UpdatePersonRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Notes,
		&i.LastInteractionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertPerson = `-- name: UpsertPerson :one
INSERT INTO persons (id, user_id, name, notes, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (id) DO UPDATE
    SET name       = EXCLUDED.name,
        notes      = EXCLUDED.notes,
        updated_at = now(),
        deleted_at = NULL
WHERE persons.updated_at <= EXCLUDED.updated_at
RETURNING id, user_id, name, notes, last_interaction_date, created_at, updated_at, deleted_at
`

type UpsertPersonParams struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.UUID      `json:"user_id"`
	Name      string         `json:"name"`
	Notes     sql.NullString `json:"notes"`
	CreatedAt time.Time      `json:"created_at"`
}

type UpsertPersonRow struct {
	ID                  uuid.UUID      `json:"id"`
	UserID              uuid.UUID      `json:"user_id"`
	Name                string         `json:"name"`
	Notes               sql.NullString `json:"notes"`
	LastInteractionDate sql.NullTime   `json:"last_interaction_date"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	DeletedAt           sql.NullTime   `json:"deleted_at"`
}

func (q *Queries) UpsertPerson(ctx context.Context, arg UpsertPersonParams) (UpsertPersonRow, error) {
	row := q.db.QueryRowContext(ctx, upsertPerson,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Notes,
		arg.CreatedAt,
	)
	var i UpsertPersonRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Notes,
		&i.LastInteractionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
