// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: persons.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const upsertPerson = `-- name: UpsertPerson :one
INSERT INTO persons (id, user_id, name, notes, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (id) DO UPDATE
    SET name       = EXCLUDED.name,
        notes      = EXCLUDED.notes,
        updated_at = now(),
        deleted_at = NULL
WHERE persons.updated_at <= EXCLUDED.updated_at
RETURNING id, user_id, name, notes, last_interaction_date, created_at, updated_at, deleted_at`

type UpsertPersonParams struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	Name      string     `json:"name"`
	Notes     *string    `json:"notes"`
	CreatedAt time.Time  `json:"created_at"`
}

func (q *Queries) UpsertPerson(ctx context.Context, arg UpsertPersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, upsertPerson,
		arg.ID, arg.UserID, arg.Name, arg.Notes, arg.CreatedAt,
	)
	var i Person
	err := row.Scan(
		&i.ID, &i.UserID, &i.Name, &i.Notes,
		&i.LastInteractionDate, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
	)
	return i, err
}

const softDeletePerson = `-- name: SoftDeletePerson :one
UPDATE persons
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, name, notes, last_interaction_date, created_at, updated_at, deleted_at`

func (q *Queries) SoftDeletePerson(ctx context.Context, id, userID uuid.UUID) (Person, error) {
	row := q.db.QueryRow(ctx, softDeletePerson, id, userID)
	var i Person
	err := row.Scan(
		&i.ID, &i.UserID, &i.Name, &i.Notes,
		&i.LastInteractionDate, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
	)
	return i, err
}

const getPersonsByUpdatedSince = `-- name: GetPersonsByUpdatedSince :many
SELECT id, user_id, name, notes, last_interaction_date, created_at, updated_at, deleted_at
FROM persons
WHERE user_id = $1 AND updated_at > $2
ORDER BY updated_at ASC
LIMIT $3`

type GetPersonsByUpdatedSinceParams struct {
	UserID    uuid.UUID `json:"user_id"`
	UpdatedAt time.Time `json:"updated_at"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) GetPersonsByUpdatedSince(ctx context.Context, arg GetPersonsByUpdatedSinceParams) ([]Person, error) {
	rows, err := q.db.Query(ctx, getPersonsByUpdatedSince, arg.UserID, arg.UpdatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID, &i.UserID, &i.Name, &i.Notes,
			&i.LastInteractionDate, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const listPersons = `-- name: ListPersons :many
SELECT id, user_id, name, notes, last_interaction_date, created_at, updated_at, deleted_at
FROM persons
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY name ASC
LIMIT $2 OFFSET $3`

type ListPersonsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListPersons(ctx context.Context, arg ListPersonsParams) ([]Person, error) {
	rows, err := q.db.Query(ctx, listPersons, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID, &i.UserID, &i.Name, &i.Notes,
			&i.LastInteractionDate, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const searchPersons = `-- name: SearchPersons :many
SELECT id, user_id, name, notes, last_interaction_date, created_at, updated_at, deleted_at
FROM persons
WHERE user_id = $1
  AND deleted_at IS NULL
  AND search_vector @@ plainto_tsquery('english', $2)
ORDER BY ts_rank(search_vector, plainto_tsquery('english', $2)) DESC
LIMIT 50`

func (q *Queries) SearchPersons(ctx context.Context, userID uuid.UUID, query string) ([]Person, error) {
	rows, err := q.db.Query(ctx, searchPersons, userID, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID, &i.UserID, &i.Name, &i.Notes,
			&i.LastInteractionDate, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getPersonByID = `-- name: GetPersonByID :one
SELECT id, user_id, name, notes, last_interaction_date, created_at, updated_at, deleted_at
FROM persons
WHERE id = $1 AND user_id = $2
LIMIT 1`

func (q *Queries) GetPersonByID(ctx context.Context, id, userID uuid.UUID) (Person, error) {
	row := q.db.QueryRow(ctx, getPersonByID, id, userID)
	var i Person
	err := row.Scan(
		&i.ID, &i.UserID, &i.Name, &i.Notes,
		&i.LastInteractionDate, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
	)
	return i, err
}

const updatePerson = `-- name: UpdatePerson :one
UPDATE persons
SET name       = coalesce($3, name),
    notes      = coalesce($4, notes),
    updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, name, notes, last_interaction_date, created_at, updated_at, deleted_at`

type UpdatePersonParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Name   *string   `json:"name"`
	Notes  *string   `json:"notes"`
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, updatePerson, arg.ID, arg.UserID, arg.Name, arg.Notes)
	var i Person
	err := row.Scan(
		&i.ID, &i.UserID, &i.Name, &i.Notes,
		&i.LastInteractionDate, &i.CreatedAt, &i.UpdatedAt, &i.DeletedAt,
	)
	return i, err
}
