// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: settings.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getOrCreateUserSettings = `-- name: GetOrCreateUserSettings :one
INSERT INTO user_settings (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO UPDATE
    SET user_id = EXCLUDED.user_id
RETURNING id, user_id, notifications_enabled, default_follow_up_days, inactivity_follow_ups_enabled, inactivity_threshold_days, created_at, updated_at`

func (q *Queries) GetOrCreateUserSettings(ctx context.Context, userID uuid.UUID) (UserSetting, error) {
	row := q.db.QueryRow(ctx, getOrCreateUserSettings, userID)
	var i UserSetting
	err := row.Scan(
		&i.ID, &i.UserID, &i.NotificationsEnabled, &i.DefaultFollowUpDays,
		&i.InactivityFollowUpsEnabled, &i.InactivityThresholdDays,
		&i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const updateUserSettings = `-- name: UpdateUserSettings :one
UPDATE user_settings
SET notifications_enabled         = coalesce($2, notifications_enabled),
    default_follow_up_days        = coalesce($3, default_follow_up_days),
    inactivity_follow_ups_enabled = coalesce($4, inactivity_follow_ups_enabled),
    inactivity_threshold_days     = coalesce($5, inactivity_threshold_days),
    updated_at                    = now()
WHERE user_id = $1
RETURNING id, user_id, notifications_enabled, default_follow_up_days, inactivity_follow_ups_enabled, inactivity_threshold_days, created_at, updated_at`

type UpdateUserSettingsParams struct {
	UserID                      uuid.UUID `json:"user_id"`
	NotificationsEnabled        *bool     `json:"notifications_enabled"`
	DefaultFollowUpDays         *int32    `json:"default_follow_up_days"`
	InactivityFollowUpsEnabled  *bool     `json:"inactivity_follow_ups_enabled"`
	InactivityThresholdDays     *int32    `json:"inactivity_threshold_days"`
}

func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (UserSetting, error) {
	row := q.db.QueryRow(ctx, updateUserSettings,
		arg.UserID, arg.NotificationsEnabled, arg.DefaultFollowUpDays,
		arg.InactivityFollowUpsEnabled, arg.InactivityThresholdDays,
	)
	var i UserSetting
	err := row.Scan(
		&i.ID, &i.UserID, &i.NotificationsEnabled, &i.DefaultFollowUpDays,
		&i.InactivityFollowUpsEnabled, &i.InactivityThresholdDays,
		&i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}
