// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: sync.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const upsertSyncMetadata = `-- name: UpsertSyncMetadata :one
INSERT INTO sync_metadata (user_id, entity_type, device_id, last_sync_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, entity_type, device_id) DO UPDATE
    SET last_sync_at = EXCLUDED.last_sync_at,
        updated_at   = now()
RETURNING id, user_id, entity_type, device_id, last_sync_at, updated_at`

type UpsertSyncMetadataParams struct {
	UserID     uuid.UUID `json:"user_id"`
	EntityType string    `json:"entity_type"`
	DeviceID   string    `json:"device_id"`
	LastSyncAt time.Time `json:"last_sync_at"`
}

func (q *Queries) UpsertSyncMetadata(ctx context.Context, arg UpsertSyncMetadataParams) (SyncMetadatum, error) {
	row := q.db.QueryRow(ctx, upsertSyncMetadata,
		arg.UserID, arg.EntityType, arg.DeviceID, arg.LastSyncAt,
	)
	var i SyncMetadatum
	err := row.Scan(
		&i.ID, &i.UserID, &i.EntityType, &i.DeviceID, &i.LastSyncAt, &i.UpdatedAt,
	)
	return i, err
}

const replaceLogPersonLinks = `-- name: ReplaceLogPersonLinks :exec
WITH deleted AS (
    DELETE FROM log_person_links
    WHERE log_id = $1
)
INSERT INTO log_person_links (log_id, person_id, user_id)
SELECT $1, unnest($2::uuid[]), $3`

type ReplaceLogPersonLinksParams struct {
	LogID     uuid.UUID   `json:"log_id"`
	PersonIDs []uuid.UUID `json:"person_ids"`
	UserID    uuid.UUID   `json:"user_id"`
}

func (q *Queries) ReplaceLogPersonLinks(ctx context.Context, arg ReplaceLogPersonLinksParams) error {
	_, err := q.db.Exec(ctx, replaceLogPersonLinks, arg.LogID, arg.PersonIDs, arg.UserID)
	return err
}

const createDeliveryRecord = `-- name: CreateDeliveryRecord :one
INSERT INTO notification_deliveries (notification_id, device_token_id, status, error_message)
VALUES ($1, $2, $3, $4)
RETURNING id, notification_id, device_token_id, status, error_message, attempted_at`

type CreateDeliveryRecordParams struct {
	NotificationID uuid.UUID  `json:"notification_id"`
	DeviceTokenID  *uuid.UUID `json:"device_token_id"`
	Status         string     `json:"status"`
	ErrorMessage   *string    `json:"error_message"`
}

func (q *Queries) CreateDeliveryRecord(ctx context.Context, arg CreateDeliveryRecordParams) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, createDeliveryRecord,
		arg.NotificationID, arg.DeviceTokenID, arg.Status, arg.ErrorMessage,
	)
	return scanNotificationDelivery(row)
}
